### ISSUE TITLE
Expected to be an indonesian result instead an english result

### ISSUE THREAD

**Issue by imniwa** [caesariodito/mp-assignment-automation#12]
I've tested using Indonesian lang as an input then the generated result it's not as expected. expecting to be an Indonesian lang result but instead an English result.

![image](https://user-images.githubusercontent.com/42795054/218030867-23681c97-6c98-4fc3-99d5-422e10d79e01.png)

---
anyways it's a fantastic project, sir. 
---

OOT. I've some suggestions to improve the UX app system. 
- we can add a link instead of uploading a document or image.

**Comment by caesariodito** [comment]
Thank you for your feedback!

I'll fix the bug and add your suggested feature later.

I appreciate your effort in trying this project!

**Comment by caesariodito** [comment]
Fully fix.

Once more, I appreciate your feedback. Thank you.
